name: depth_trade
description: "DepthTrade - Automated Grid Trading Platform based on BitgetBot"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1

  uuid: ^4.5.1
  url_launcher: ^6.3.1
  http: ^1.2.2
  crypto: ^3.0.6
  intl: ^0.19.0
  fl_chart: ^0.70.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
